use_frameworks!

platform :ios, '8.0'

target 'LMUI_Example' do
  pod 'LMUI', :path => '../'

  target 'LMUI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
